#!/usr/bin/env python3

import os
import re
import sys
import array

print("// This file is auto-generated by make-assets.py.")

# Print all input files as char arrays in hex format.
for filename in sys.argv[1:]:
      
        bytes = array.array('B', open(filename, "rb").read())
        size = len(bytes)
        
        filename = os.path.basename(filename)
        sanfilename = filename.replace('.','')
        
        print("")
        output = "const unsigned char %s[%d] = {\n" % (sanfilename, size)

        pos = 0
        size = len(bytes)
        for byte in bytes:
                if (pos % 11) == 0:
                        output += "        "
                output += "0x%02x" % (byte)
                if (pos + 1) == size:
                        output += '\n'
                elif (pos % 11) == 10:
                        output += ',\n'
                elif (pos + 1) < size:
                        output += ", "
                pos += 1

        output += "};"

        print(output)